CREATE TABLE menu_items (
    id_menu_item INT AUTO_INCREMENT PRIMARY KEY,
    name_item VARCHAR(150) NOT NULL,
    category_item VARCHAR(100) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    stock INT NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
