CREATE TABLE reservation_rooms (
    id_reservation_room INT AUTO_INCREMENT PRIMARY KEY,
    seats INT NOT NULL,
    price_place DECIMAL(10,2) NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
